In [49]:
import pandas as pd

In [50]:
import numpy as np

In [51]:
import csv

In [52]:
from sklearn.model_selection import train_test_split
all_data = pd.read_csv('data.csv',index_col=0)
all_data.head()
print(all_data)

          diagnostico  radio_medio  textura_media  perimetro_medio  \
id                                                                   
842302              0        17.99          10.38           122.80   
842517              0        20.57          17.77           132.90   
84300903            0        19.69          21.25           130.00   
84348301            0        11.42          20.38            77.58   
84358402            0        20.29          14.34           135.10   
...               ...          ...            ...              ...   
926424              0        21.56          22.39           142.00   
926682              0        20.13          28.25           131.20   
926954              0        16.60          28.08           108.30   
927241              0        20.60          29.33           140.10   
92751               1         7.76          24.54            47.92   

          area_media  suavidad_media  compactacion_media  concavidad_media  \
id         

In [53]:
print(all_data.columns)

Index(['diagnostico', 'radio_medio', 'textura_media', 'perimetro_medio',
       'area_media', 'suavidad_media', 'compactacion_media',
       'concavidad_media', 'puntos_concavos_medios', 'simetria_media',
       'dimension_fractal_media', 'radio_se', 'textura_se', 'perimetro_se',
       'area_se', 'suavidad_se', 'compactacion_se', 'concavidad_se',
       'concavidad_puntos_se', 'simetria_se', 'fractal_dimension_se',
       'radio_peor', 'textura_peor', 'perimetro_peor', 'area_peor',
       'suavidad_peor', 'compactacion_peor', 'concavidad_peor',
       'concavidad_punto_peor', 'simetria_peor', 'fractal_dimension_peor'],
      dtype='object')


In [54]:
all_inputs = all_data.iloc[:, 1:32].values
all_outputs = all_data.iloc[:, 0].values

# Dividir en un conjunto de entrenamiento y uno de prueba
X_train, X_test, Y_train, Y_test = train_test_split(all_inputs, all_outputs,
    test_size=1/30)

n = X_train.shape[0] # número de registros de entrenamiento



In [55]:
print(all_outputs)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [56]:
print(all_inputs)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e+02 2.750e+02 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e+02 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e+02 4.087e-01 1.240e+02]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [57]:
print(all_outputs)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [58]:
n = X_train.shape[0] # número de registros de entrenamiento

In [59]:
 #Construir una red neuronal con pesos y sesgos
#w_hidden = np.random.rand(3, 3)
w_hidden = np.random.rand(30, 30)
w_output = np.random.rand(1, 30)

b_hidden = np.random.rand(30, 1)
b_output = np.random.rand(1, 1)


In [60]:
X_train, X_test, Y_train, Y_test = train_test_split(all_inputs, all_outputs,
    test_size=1/3)

n = X_train.shape[0] # número de registros de entrenamiento


In [61]:
# Funciones de activacion
relu = lambda x: np.maximum(x, 0)
logistic = lambda x: 1 / (1 + np.exp(-x))

In [62]:
# Funcion que corre la red neuronal con los datos de entrada para predecir la salida
def forward_prop(X):
    Z1 = w_hidden @ X + b_hidden
    A1 = relu(Z1)
    Z2 = w_output @ A1 + b_output
    A2 = logistic(Z2)
    return Z1, A1, Z2, A2


In [63]:
test_predictions = forward_prop(X_test.transpose())[3] # me interesa solo la capa de salida, A2
test_comparisons = np.equal((test_predictions >= .5).flatten().astype(int), Y_test)
accuracy = sum(test_comparisons.astype(int) / X_test.shape[0])
print("ACCURACY: ", accuracy)


ACCURACY:  0.5842105263157903


In [64]:
w_hidden = np.random.rand(30, 30)
print('w_hidden = ', w_hidden)



w_hidden =  [[0.53246946 0.15703923 0.10861508 0.27421197 0.74316048 0.09993777
  0.53439697 0.407221   0.07469262 0.88580399 0.30234733 0.80580651
  0.7183741  0.14589794 0.13083831 0.47835156 0.39452374 0.5617106
  0.38038033 0.42120516 0.11848445 0.50751133 0.35166803 0.83352413
  0.2934283  0.51413258 0.0773314  0.31853239 0.05298777 0.70495652]
 [0.47747997 0.64285453 0.82118657 0.30833133 0.44393284 0.24079891
  0.14782741 0.52687915 0.65686595 0.02088289 0.11037453 0.98300332
  0.0798913  0.26721087 0.70671959 0.2214082  0.22791714 0.77087531
  0.65956737 0.12450493 0.90695935 0.26191468 0.31710393 0.07314009
  0.33999746 0.58866382 0.06735459 0.94599099 0.07780995 0.78899064]
 [0.80482014 0.80532709 0.81720505 0.73381847 0.19908299 0.99290108
  0.47793967 0.65488617 0.70621222 0.24340585 0.97315844 0.01605576
  0.99160992 0.505154   0.80606406 0.0475443  0.12132511 0.18202369
  0.98524879 0.78418055 0.65687215 0.72983235 0.56443602 0.37919314
  0.62226524 0.18366778 0.23562483 

In [65]:
w_output = np.random.rand(1, 30)
print('w_output = ', w_output)

w_output =  [[0.00173485 0.91703512 0.93119381 0.58404109 0.79988625 0.35519802
  0.40747208 0.87703246 0.53247572 0.75658611 0.96471511 0.16664783
  0.13215778 0.77164344 0.96581194 0.86221038 0.51306705 0.67654954
  0.20627499 0.65059734 0.77538099 0.1251351  0.79517629 0.1398851
  0.23527431 0.39823491 0.94315048 0.44911375 0.88302698 0.21248697]]


In [66]:
b_hidden = np.random.rand(30, 1)
print('b_hidden = ', b_hidden)



b_hidden =  [[0.24261176]
 [0.82812988]
 [0.91743571]
 [0.03606674]
 [0.69915964]
 [0.49319578]
 [0.01710382]
 [0.53114255]
 [0.01509653]
 [0.43296889]
 [0.01364581]
 [0.27540023]
 [0.50696807]
 [0.63593661]
 [0.10070068]
 [0.45961438]
 [0.28058195]
 [0.36132696]
 [0.40835762]
 [0.18811431]
 [0.29884842]
 [0.53677329]
 [0.98918178]
 [0.45503553]
 [0.4915044 ]
 [0.41208515]
 [0.29668002]
 [0.72598774]
 [0.57743802]
 [0.34254452]]


In [67]:
b_output = np.random.rand(1, 1)
print('b_output = ', b_output)

b_output =  [[0.11073792]]


In [68]:

from sympy import *

W1, W2, B1, B2, A1, A2, Z1, Z2, X, Y = \
    symbols('W1 W2 B1 B2 A1 A2 Z1 Z2 X Y')

# Derivada de la función costo respecto A2
C = (A2 - Y)**2
dC_dA2 = diff(C, A2)
print("dC_dA2 = ", dC_dA2) # 2*A2 - 2*Y

# Derivada de A2 respecto de Z2
logistic = lambda x: 1 / (1 + exp(-x))
_A2 = logistic(Z2)
dA2_dZ2 = diff(_A2, Z2)
print("dA2_dZ2 = ", dA2_dZ2) # exp(-Z2)/(1 + exp(-Z2))**2

# Derivada de Z2 respecto a A1
_Z2 = A1*W2 + B2
dZ2_dA1 = diff(_Z2, A1)
print("dZ2_dA1 = ", dZ2_dA1) # W2

# Derivada de Z2 respecto a W2
dZ2_dW2 = diff(_Z2, W2)
print("dZ2_dW2 = ", dZ2_dW2) # A1

# Derivada de Z2 respecto a B2
dZ2_dB2 = diff(_Z2, B2)
print("dZ2_dB2 = ", dZ2_dB2) # 1

# Derivada de A1 respecto de Z1
relu = lambda x: Max(x, 0)
_A1 = relu(Z1)

d_relu = lambda x: x > 0 # Pendiente es 1 para los positivos, 0 para los negativos
dA1_dZ1 = d_relu(Z1)
print("dA1_dZ1 = ", dA1_dZ1) # Z1 > 0

# Derivada de Z1 respecto a W1
_Z1 = X*W1 + B1
dZ1_dW1 = diff(_Z1, W1)
print("dZ1_dW1 = ", dZ1_dW1) # X

# Derivada de Z1 respecto a B1
dZ1_dB1 = diff(_Z1, B1)
print("dZ1_dB1 = ", dZ1_dB1) # 1

dC_dA2 =  2*A2 - 2*Y
dA2_dZ2 =  exp(-Z2)/(1 + exp(-Z2))**2
dZ2_dA1 =  W2
dZ2_dW2 =  A1
dZ2_dB2 =  1
dA1_dZ1 =  Z1 > 0
dZ1_dW1 =  X
dZ1_dB1 =  1


In [72]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
all_data = pd.read_csv('data.csv',index_col=0)



L = 0.05  # La tasa de aprendizaje

all_inputs = all_data.iloc[:, 1:32].values
all_outputs = all_data.iloc[:, 0].values


# Dividir los conjuntos de datos de entrenamiento y prueba
X_train, X_test, Y_train, Y_test = train_test_split(all_inputs, all_outputs,
    test_size=1 / 3)
n = X_train.shape[0]
print(n)

# Construir red neuronal con pesos y sesgos
# inicializados aleatoriamente
np.random.seed(0)
w_hidden = np.random.rand(30, 30)
w_output = np.random.rand(1, 30)

b_hidden = np.random.rand(30, 1)
b_output = np.random.rand(1, 1)

# Funciones de activación
relu = lambda x: np.maximum(x, 0)
logistic = lambda x: 1 / (1 + np.exp(-x))

# Ejecutar entradas a través de la red neuronal para obtener salidas predichas
def forward_prop(X):
    Z1 = w_hidden @ X + b_hidden
    A1 = relu(Z1)
    Z2 = w_output @ A1 + b_output
    A2 = logistic(Z2)
    return Z1, A1, Z2, A2

# Derivadas de las funciones de activación
d_relu = lambda x: x > 0
d_logistic = lambda x: np.exp(-x) / (1 + np.exp(-x)) ** 2

# Devuelve pendientes para pesos y sesgos
# usando la regla de la cadena
def backward_prop(Z1, A1, Z2, A2, X, Y):
    dC_dA2 = 2 * A2 - 2 * Y
    dA2_dZ2 = d_logistic(Z2)
    dZ2_dA1 = w_output
    dZ2_dW2 = A1
    dZ2_dB2 = 1
    dA1_dZ1 = d_relu(Z1)
    dZ1_dW1 = X
    dZ1_dB1 = 1
    dC_dW2 = dC_dA2 @ dA2_dZ2 @ dZ2_dW2.T

    dC_dB2 = dC_dA2 @ dA2_dZ2 * dZ2_dB2

    dC_dA1 = dC_dA2 @ dA2_dZ2 @ dZ2_dA1

    dC_dW1 = dC_dA1 @ dA1_dZ1 @ dZ1_dW1.T

    dC_dB1 = dC_dA1 @ dA1_dZ1 * dZ1_dB1

    return dC_dW1, dC_dB1, dC_dW2, dC_dB2

# Ejecutar descenso de gradiente
for i in range(100_000):
    # seleccionar aleatoriamente uno de los datos de entrenamiento
    idx = np.random.choice(n, 1, replace=False)
    X_sample = X_train[idx].transpose()
    Y_sample = Y_train[idx]

    # pasar datos seleccionados aleatoriamente a través de la red neuronal
    Z1, A1, Z2, A2 = forward_prop(X_sample)

    # distribuir error a través de la retropropagación
    # y devolver pendientes para pesos y sesgos
    dW1, dB1, dW2, dB2 = backward_prop(Z1, A1, Z2, A2, X_sample, Y_sample)

    # actualizar pesos y sesgos
    w_hidden -= L * dW1
    b_hidden -= L * dB1
    w_output -= L * dW2
    b_output -= L * dB2

379


In [70]:
def predict_probability(radio_medio, textura_media, perimetro_medio,
                        area_media, suavidad_media, compactacion_media,
                        concavidad_media, puntos_concavos_medios, simetria_media,
                        dimension_fractal_media, radio_se, textura_se, perimetro_se,
                        area_se, suavidad_se, compactacion_se, concavidad_se,
                        concavidad_puntos_se, simetria_se, fractal_dimension_se,
                        radio_peor, textura_peor, perimetro_peor, area_peor,
                        suavidad_peor, compactacion_peor, concavidad_peor,
                        concavidad_punto_peor, simetria_peor, fractal_dimension_peor):
    X = np.array([[radio_medio, textura_media, perimetro_medio,
                   area_media, suavidad_media, compactacion_media,
                   concavidad_media, puntos_concavos_medios, simetria_media,
                   dimension_fractal_media, radio_se, textura_se, perimetro_se,
                   area_se, suavidad_se, compactacion_se, concavidad_se,
                   concavidad_puntos_se, simetria_se, fractal_dimension_se,
                   radio_peor, textura_peor, perimetro_peor, area_peor,
                   suavidad_peor, compactacion_peor, concavidad_peor,
                   concavidad_punto_peor, simetria_peor, fractal_dimension_peor]]).transpose()
    Z1, A1, Z2, A2 = forward_prop(X)
    return A2



"""""
#opcion1   84358402  0  tiene cancer
radio_medio=20.29
textura_media=14.34
perimetro_medio=135.1
area_media=1297
suavidad_media=0.1003
compactacion_media=0.132
concavidad_media=198
puntos_concavos_medios=0.1043
simetria_media=0.1809
dimension_fractal_media=20.30
radio_se=14.35
textura_se=135.2
perimetro_se=1298
area_se=0.1004
suavidad_se=0.1329
compactacion_se=199
concavidad_se=0.1044
concavidad_puntos_se=0.1810
simetria_se=20.31
fractal_dimension_se=14.36
radio_peor=135.3
textura_peor=1299
perimetro_peor=0.1005
area_peor=0.1330
suavidad_peor=2000
compactacion_peor=0.1045
concavidad_peor=0.1811
concavidad_punto_peor=20.32
simetria_peor=14.37
fractal_dimension_peor=135.4
"""""

#opcion2 id 8510653 1 no tiene cancer
radio_medio=13.08
textura_media=15.71
perimetro_medio=85.63
area_media=520
suavidad_media=0.1075
compactacion_media=127
concavidad_media=0.04568
puntos_concavos_medios=0.0311
simetria_media=0.1967
dimension_fractal_media=0.06811
radio_se=0.1852
textura_se=0.7477
perimetro_se=1383
area_se=14.67
suavidad_se=0.004097
compactacion_se=0.01898
concavidad_se=0.01698
concavidad_puntos_se=0.00649
simetria_se=0.01678
fractal_dimension_se=0.002425
radio_peor=14.5
textura_peor=20.49
perimetro_peor=96.09
area_peor=630.5
suavidad_peor=0.1312
compactacion_peor=0.2776
concavidad_peor=189
concavidad_punto_peor=0.07283
simetria_peor=0.3184
fractal_dimension_peor=0.08183


# Llama a la función predict_probability con los valores de las características
probabilidad_tener_cancer = predict_probability(radio_medio, textura_media, perimetro_medio,
                        area_media, suavidad_media, compactacion_media,
                        concavidad_media, puntos_concavos_medios, simetria_media,
                        dimension_fractal_media, radio_se, textura_se, perimetro_se,
                        area_se, suavidad_se, compactacion_se, concavidad_se,
                        concavidad_puntos_se, simetria_se, fractal_dimension_se,
                        radio_peor, textura_peor, perimetro_peor, area_peor,
                        suavidad_peor, compactacion_peor, concavidad_peor,
                        concavidad_punto_peor, simetria_peor, fractal_dimension_peor)
if A2 > 0.5:
    # Si la condición es verdadera, ejecutar este bloque de código
    print("tiene cancer.")
else:
    # Si la condición es falsa, ejecutar este bloque de código
    print("no tiene cancer.")



print("Probabilidad de tener cáncer:", probabilidad_tener_cancer)



tiene cancer.
Probabilidad de tener cáncer: [[1.]]
